/*
    Functions in this file are responsible for communicating with VirusTotal API (v3).

    VirusTotal requests carry both a reusable credential and, for uploads, user-selected file
    contents. Keep every destination and redirect decision in this module so configuration or an
    API response cannot redirect either value to another origin.
*/
use crate::host_file;
use crate::structs::VirusTotalApiPathStruct;
use crate::virustotal_api_structs::VtEndpoint;
use reqwest::multipart;
use reqwest::{Client, RequestBuilder, Url};
use std::error::Error;
use std::time::Duration;
use tokio::time::timeout;

pub(crate) async fn run_cli(
    args: &crate::cli::Args,
    settings: &crate::structs::Settings,
) -> Result<(), Box<dyn Error>> {
    let api_key = &settings.run_settings.vt_api;
    if api_key.trim().is_empty() {
        return Err("VirusTotal operation requested but run_settings.vt_api is empty".into());
    }
    let empty_url = String::new();

    if let Some(analysis_id) = args.vta.as_deref() {
        let (status, body) = call_api(
            &settings.virus_total_api.analyze_result,
            api_key,
            &VtEndpoint::Analysis,
            None,
            Some(analysis_id),
            &empty_url,
        )
        .await?;
        if !status.is_success() {
            return Err(format!("VirusTotal returned HTTP {status}: {body:?}").into());
        }
        let json: serde_json::Value = serde_json::from_str(&body)?;
        let destination = crate::utils::write_json_to_file(&serde_json::to_string_pretty(&json)?)?;
        println!(
            "[cli] VirusTotal analysis written to {}",
            crate::utils::terminal_safe(&destination.display().to_string())
        );
        return Ok(());
    }

    if let Some(file) = args.vtl.as_deref() {
        let (status, body) = call_api(
            &settings.virus_total_api.get_url_large,
            api_key,
            &VtEndpoint::GetLargeUrl,
            Some(file),
            None,
            &empty_url,
        )
        .await?;
        if !status.is_success() {
            return Err(format!("VirusTotal returned HTTP {status}: {body:?}").into());
        }
        let json: serde_json::Value = serde_json::from_str(&body)?;
        let upload_url = json
            .pointer("/data")
            .and_then(serde_json::Value::as_str)
            .ok_or("VirusTotal large-file response did not contain data")?
            .to_string();
        let response = call_api(
            &settings.virus_total_api.upload_large,
            api_key,
            &VtEndpoint::ScanLargeFile,
            Some(file),
            None,
            &upload_url,
        )
        .await;
        let destination = crate::utils::handle_vt_response(response, args.debug, settings).await?;
        println!(
            "[cli] VirusTotal analysis written to {}",
            crate::utils::terminal_safe(&destination.display().to_string())
        );
        return Ok(());
    }

    let small_file = args
        .vts
        .as_deref()
        .or_else(|| args.vt.then_some(args.path.as_deref()).flatten());
    let small_file = small_file.ok_or("--vt requires --path")?;
    let response = call_api(
        &settings.virus_total_api.upload_small,
        api_key,
        &VtEndpoint::UploadSmall,
        Some(small_file),
        None,
        &empty_url,
    )
    .await;
    let destination = crate::utils::handle_vt_response(response, args.debug, settings).await?;
    println!(
        "[cli] VirusTotal analysis written to {}",
        crate::utils::terminal_safe(&destination.display().to_string())
    );
    Ok(())
}

const SMALL_FILE_SIZE_CAP: u64 = 32 * 1024 * 1024;
const LARGE_FILE_SIZE_CAP: u64 = 600 * 1024 * 1024;
const RESPONSE_SIZE_CAP: usize = 1024 * 1024;
const MAX_DYNAMIC_URL_BYTES: usize = 16 * 1024;
const MAX_ANALYSIS_ID_BYTES: usize = 1024;
const REQUEST_TIMEOUT: Duration = Duration::from_secs(30);
const CONNECT_TIMEOUT: Duration = Duration::from_secs(10);

const VIRUSTOTAL_HOST: &str = "www.virustotal.com";
const VIRUSTOTAL_HTTPS_PORT: u16 = 443;
const UPLOAD_SMALL_URL: &str = "https://www.virustotal.com/api/v3/files";
const GET_LARGE_UPLOAD_URL: &str = "https://www.virustotal.com/api/v3/files/upload_url";
const ANALYSIS_URL: &str = "https://www.virustotal.com/api/v3/analyses";
const DYNAMIC_UPLOAD_SETTING: &str = "custom - generated by get_url_large";

type VtResponse = Result<(reqwest::StatusCode, String), Box<dyn Error>>;

struct UploadFile {
    file: tokio::fs::File,
    len: u64,
    file_name: String,
}

fn build_client() -> Result<Client, Box<dyn Error>> {
    Ok(Client::builder()
        .redirect(reqwest::redirect::Policy::none())
        .https_only(true)
        .no_proxy()
        .no_gzip()
        .no_brotli()
        .no_zstd()
        .no_deflate()
        .connect_timeout(CONNECT_TIMEOUT)
        .timeout(REQUEST_TIMEOUT)
        .build()?)
}

async fn send_file(url: Url, api_key: &str, upload: UploadFile) -> VtResponse {
    let client = build_client()?;
    let part = multipart::Part::stream_with_length(upload.file, upload.len)
        .file_name(upload.file_name)
        .mime_str("application/octet-stream")?;
    let form = multipart::Form::new().part("file", part);

    println!("[virustotal] uploading selected file to VirusTotal");
    execute_bounded(client.post(url).header("X-Apikey", api_key).multipart(form)).await
}

async fn send_get(url: Url, api_key: &str) -> VtResponse {
    let client = build_client()?;
    execute_bounded(client.get(url).header("X-Apikey", api_key)).await
}

async fn execute_bounded(request: RequestBuilder) -> VtResponse {
    let operation = async move {
        let mut response = request.send().await?;
        let status = response.status();

        if let Some(length) = response.content_length()
            && length > RESPONSE_SIZE_CAP as u64
        {
            return Err(format!(
                "VirusTotal response declared {length} bytes; limit is {RESPONSE_SIZE_CAP} bytes"
            )
            .into());
        }

        let mut body = Vec::with_capacity(
            response
                .content_length()
                .unwrap_or(0)
                .min(RESPONSE_SIZE_CAP as u64) as usize,
        );
        while let Some(chunk) = response.chunk().await? {
            append_bounded(&mut body, &chunk, RESPONSE_SIZE_CAP)?;
        }

        let body = String::from_utf8(body)
            .map_err(|error| format!("VirusTotal returned a non-UTF-8 response: {error}"))?;
        Ok((status, body))
    };

    match timeout(REQUEST_TIMEOUT, operation).await {
        Ok(result) => result,
        Err(_) => Err(format!(
            "VirusTotal request exceeded the {} second total deadline",
            REQUEST_TIMEOUT.as_secs()
        )
        .into()),
    }
}

fn append_bounded(
    destination: &mut Vec<u8>,
    chunk: &[u8],
    maximum: usize,
) -> Result<(), Box<dyn Error>> {
    let new_len = destination
        .len()
        .checked_add(chunk.len())
        .ok_or("VirusTotal response size overflow")?;
    if new_len > maximum {
        return Err(format!("VirusTotal response exceeded the {maximum} byte limit").into());
    }
    destination.extend_from_slice(chunk);
    Ok(())
}

/// Handles the supported calls to the VirusTotal API.
///
/// The URLs in settings are accepted only when they exactly match the compiled-in API endpoints.
/// The one-time large upload URL is separately restricted to the same HTTPS origin and port.
pub async fn call_api(
    path: &VirusTotalApiPathStruct,
    api_key: &str,
    endpoint: &VtEndpoint,
    file_path: Option<&str>,
    analysis_id: Option<&str>,
    new_url: &str,
) -> VtResponse {
    match endpoint {
        VtEndpoint::UploadSmall => {
            let url = configured_endpoint_url(path, endpoint)?;
            let file_path = file_path.ok_or("small-file upload requires a file path")?;
            let upload = open_upload_file(file_path, SMALL_FILE_SIZE_CAP)?;
            send_file(url, api_key, upload).await
        }
        VtEndpoint::GetLargeUrl => {
            let url = configured_endpoint_url(path, endpoint)?;
            send_get(url, api_key).await
        }
        VtEndpoint::ScanLargeFile => {
            if path.url != DYNAMIC_UPLOAD_SETTING {
                return Err(
                    "the configured large-upload URL must be generated by VirusTotal".into(),
                );
            }
            let url = validate_virustotal_url(new_url, true)?;
            let file_path = file_path.ok_or("large-file upload requires a file path")?;
            let upload = open_upload_file(file_path, LARGE_FILE_SIZE_CAP)?;
            send_file(url, api_key, upload).await
        }
        VtEndpoint::Analysis => {
            let base_url = configured_endpoint_url(path, endpoint)?;
            let analysis_id = analysis_id.ok_or("analysis lookup requires an analysis ID")?;
            let url = analysis_url(base_url, analysis_id)?;
            send_get(url, api_key).await
        }
    }
}

fn configured_endpoint_url(
    path: &VirusTotalApiPathStruct,
    endpoint: &VtEndpoint,
) -> Result<Url, Box<dyn Error>> {
    let expected = match endpoint {
        VtEndpoint::UploadSmall => UPLOAD_SMALL_URL,
        VtEndpoint::GetLargeUrl => GET_LARGE_UPLOAD_URL,
        VtEndpoint::Analysis => ANALYSIS_URL,
        VtEndpoint::ScanLargeFile => {
            return Err("large uploads require a one-time VirusTotal URL".into());
        }
    };

    if path.url != expected {
        return Err(format!(
            "refusing non-standard VirusTotal endpoint for {}",
            endpoint_name(endpoint)
        )
        .into());
    }
    validate_virustotal_url(expected, false)
}

fn endpoint_name(endpoint: &VtEndpoint) -> &'static str {
    match endpoint {
        VtEndpoint::UploadSmall => "small-file upload",
        VtEndpoint::GetLargeUrl => "large-upload URL retrieval",
        VtEndpoint::ScanLargeFile => "large-file upload",
        VtEndpoint::Analysis => "analysis retrieval",
    }
}

fn validate_virustotal_url(raw_url: &str, dynamic: bool) -> Result<Url, Box<dyn Error>> {
    if raw_url.len() > MAX_DYNAMIC_URL_BYTES {
        return Err("VirusTotal URL is unreasonably long".into());
    }
    let url = Url::parse(raw_url).map_err(|error| format!("invalid VirusTotal URL: {error}"))?;

    if !has_exact_virustotal_authority(raw_url)
        || url.scheme() != "https"
        || url.host_str() != Some(VIRUSTOTAL_HOST)
        || url.port_or_known_default() != Some(VIRUSTOTAL_HTTPS_PORT)
        || !url.username().is_empty()
        || url.password().is_some()
        || url.fragment().is_some()
    {
        return Err(format!(
            "VirusTotal URL must use exactly https://{VIRUSTOTAL_HOST}:{VIRUSTOTAL_HTTPS_PORT} without credentials or a fragment"
        )
        .into());
    }

    if !dynamic && (url.query().is_some() || url.as_str() != raw_url) {
        return Err("configured VirusTotal endpoints must match exactly".into());
    }
    Ok(url)
}

fn has_exact_virustotal_authority(raw_url: &str) -> bool {
    let Some(remainder) = raw_url.strip_prefix("https://") else {
        return false;
    };
    let authority_end = remainder.find(['/', '?', '#']).unwrap_or(remainder.len());
    let authority = &remainder[..authority_end];
    authority == VIRUSTOTAL_HOST || authority == "www.virustotal.com:443"
}

fn analysis_url(mut base_url: Url, analysis_id: &str) -> Result<Url, Box<dyn Error>> {
    if analysis_id.is_empty()
        || analysis_id.len() > MAX_ANALYSIS_ID_BYTES
        || !analysis_id.bytes().all(|byte| {
            byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'+' | b'/' | b'=')
        })
    {
        return Err("invalid VirusTotal analysis ID".into());
    }

    base_url
        .path_segments_mut()
        .map_err(|_| "VirusTotal analysis endpoint cannot contain path segments")?
        .push(analysis_id);
    Ok(base_url)
}

fn open_upload_file(file_path: &str, maximum: u64) -> Result<UploadFile, Box<dyn Error>> {
    let input = host_file::open_pinned_input(std::path::Path::new(file_path), maximum)
        .map_err(|error| format!("cannot securely open upload file {file_path:?}: {error}"))?;

    Ok(UploadFile {
        file: tokio::fs::File::from_std(input.file),
        len: input.len,
        // Avoid disclosing a host filename in multipart metadata.
        file_name: "upload.bin".to_owned(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn endpoint(url: &str) -> VirusTotalApiPathStruct {
        VirusTotalApiPathStruct {
            method: "GET".to_owned(),
            url: url.to_owned(),
            expected: "json".to_owned(),
        }
    }

    #[test]
    fn configured_endpoints_must_match_compiled_values_exactly() {
        assert!(
            configured_endpoint_url(&endpoint(UPLOAD_SMALL_URL), &VtEndpoint::UploadSmall).is_ok()
        );
        assert!(
            configured_endpoint_url(
                &endpoint("https://attacker.invalid/collect"),
                &VtEndpoint::UploadSmall,
            )
            .is_err()
        );
        assert!(
            configured_endpoint_url(
                &endpoint("https://www.virustotal.com/api/v3/files?next=evil"),
                &VtEndpoint::UploadSmall,
            )
            .is_err()
        );
    }

    #[test]
    fn dynamic_upload_url_is_limited_to_the_vt_https_origin() {
        assert!(
            validate_virustotal_url(
                "https://www.virustotal.com/_ah/upload/one-time-token?x=1",
                true,
            )
            .is_ok()
        );

        for url in [
            "http://www.virustotal.com/_ah/upload/token",
            "https://virustotal.com/_ah/upload/token",
            "https://uploads.virustotal.com/_ah/upload/token",
            "https://www.virustotal.com.evil.invalid/upload",
            "https://www.virustotal.com:444/_ah/upload/token",
            "https://user@www.virustotal.com/_ah/upload/token",
            "https://@www.virustotal.com/_ah/upload/token",
            "https://WWW.VIRUSTOTAL.COM/_ah/upload/token",
            "https://127.0.0.1/_ah/upload/token",
            "https://www.virustotal.com/_ah/upload/token#fragment",
        ] {
            assert!(
                validate_virustotal_url(url, true).is_err(),
                "unexpectedly accepted {url}"
            );
        }
    }

    #[test]
    fn analysis_ids_are_one_encoded_path_segment() {
        let base = Url::parse(ANALYSIS_URL).unwrap();
        let url = analysis_url(base, "abc/def==").unwrap();
        assert_eq!(url.host_str(), Some(VIRUSTOTAL_HOST));
        assert_eq!(url.path(), "/api/v3/analyses/abc%2Fdef==");
        assert!(url.query().is_none());
        assert!(analysis_url(Url::parse(ANALYSIS_URL).unwrap(), "../files").is_err());
    }

    #[test]
    fn response_accumulation_stops_at_the_limit() {
        let mut body = Vec::new();
        append_bounded(&mut body, b"1234", 5).unwrap();
        assert!(append_bounded(&mut body, b"56", 5).is_err());
        assert_eq!(body, b"1234");
    }

    #[test]
    fn upload_size_is_checked_on_the_open_handle() {
        let path = std::env::temp_dir().join(format!(
            "foxhole-vt-upload-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::write(&path, b"1234").unwrap();

        let result = open_upload_file(path.to_str().unwrap(), 3);
        assert!(result.is_err());
        std::fs::remove_file(path).unwrap();
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn final_symlink_is_not_accepted_for_upload() {
        use std::os::windows::fs::symlink_file;

        let directory = std::env::temp_dir().join(format!(
            "foxhole-vt-link-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir(&directory).unwrap();
        let target = directory.join("target.bin");
        let link = directory.join("link.bin");
        std::fs::write(&target, b"test").unwrap();

        // Creating symlinks may require Developer Mode or a specific Windows privilege.
        if symlink_file(&target, &link).is_ok() {
            assert!(open_upload_file(link.to_str().unwrap(), 100).is_err());
            std::fs::remove_file(&link).unwrap();
        }
        std::fs::remove_file(&target).unwrap();
        std::fs::remove_dir(&directory).unwrap();
    }
}
